######################################################################
# Automatically generated by qmake (1.07a) Wed Dec 4 01:56:37 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += servermainwindow.h serversocket.h
INTERFACES += servermainwindowbase.ui
SOURCES += server.cpp servermainwindow.cpp serversocket.cpp
