######################################################################
# Automatically generated by qmake (1.07a) Sat Dec 7 13:38:21 2013
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += servermainwindow.h serversocket.h
INTERFACES += servermainwindowbase.ui
SOURCES += server.cpp servermainwindow.cpp serversocket.cpp
